### PR TITLE
Fix text overflow and improve social logins

### PR DESCRIPTION
**Pull request by alachaum**
**Summary**
- Fix text overflows on mobile
- Add help paragraph on social login page

Closes KEYP-5
Closes KEYP-6

### CODE REVIEW

**Review by pixernot — CHANGES_REQUESTED** [review]
Not accepted

**Review by pixernot — APPROVED** [review]

**Comment by alachaum** [comment]
Planning to release that soon

**Comment by alachaum** [comment]
Will release soon

**Comment by alachaum** [comment]
Some comment

**Comment by alachaum** [comment]
I think we're done with this one!

**Comment by alachaum** [comment]
We should merge it soon

**Pull request merged**
